"""add system_configs table

Revision ID: d9158181baf1
Revises: 012_merge_heads
Create Date: 2026-01-31 08:53:36.302134+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9158181baf1'
down_revision: Union[str, None] = '012_merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_index(op.f('ix_daily_journals_id'), 'daily_journals', ['id'], unique=False)
    op.add_column('expenses', sa.Column('type', sa.String(), server_default='expense', nullable=False))
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_mood_id'), 'mood', ['id'], unique=False)
    op.create_index(op.f('ix_reflections_date'), 'reflections', ['date'], unique=False)
    op.create_index(op.f('ix_reflections_id'), 'reflections', ['id'], unique=False)
    op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)
    op.create_index(op.f('ix_sleep_id'), 'sleep', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_id'), table_name='sleep')
    op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_date'), table_name='reflections')
    op.drop_index(op.f('ix_mood_id'), table_name='mood')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_column('expenses', 'type')
    op.drop_index(op.f('ix_daily_journals_id'), table_name='daily_journals')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###