"""add system_configs table

Revision ID: d9158181baf1
Revises: 012_merge_heads
Create Date: 2026-01-31 08:53:36.302134+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9158181baf1'
down_revision: Union[str, None] = '012_merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Helper to check if table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'system_configs' not in tables:
        op.create_table('system_configs',
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('key')
        )
        op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    
    # Check indexes on daily_journals
    daily_journals_indexes = [idx['name'] for idx in inspector.get_indexes('daily_journals')]
    if op.f('ix_daily_journals_id') not in daily_journals_indexes:
        op.create_index(op.f('ix_daily_journals_id'), 'daily_journals', ['id'], unique=False)

    # Check column 'type' on expenses
    expenses_columns = [col['name'] for col in inspector.get_columns('expenses')]
    if 'type' not in expenses_columns:
        op.add_column('expenses', sa.Column('type', sa.String(), server_default='expense', nullable=False))
    
    expenses_indexes = [idx['name'] for idx in inspector.get_indexes('expenses')]
    if op.f('ix_expenses_id') not in expenses_indexes:
        op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)

    # Check index on mood
    mood_indexes = [idx['name'] for idx in inspector.get_indexes('mood')]
    if op.f('ix_mood_id') not in mood_indexes:
        op.create_index(op.f('ix_mood_id'), 'mood', ['id'], unique=False)

    # Check indexes on reflections
    if 'reflections' in tables:
        reflections_indexes = [idx['name'] for idx in inspector.get_indexes('reflections')]
        if op.f('ix_reflections_date') not in reflections_indexes:
            op.create_index(op.f('ix_reflections_date'), 'reflections', ['date'], unique=False)
        if op.f('ix_reflections_id') not in reflections_indexes:
            op.create_index(op.f('ix_reflections_id'), 'reflections', ['id'], unique=False)
        if op.f('ix_reflections_user_id') not in reflections_indexes:
            op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)

    # Check index on sleep
    sleep_indexes = [idx['name'] for idx in inspector.get_indexes('sleep')]
    if op.f('ix_sleep_id') not in sleep_indexes:
        op.create_index(op.f('ix_sleep_id'), 'sleep', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check indices/tables before dropping
    tables = inspector.get_table_names()

    if 'sleep' in tables:
        sleep_indexes = [idx['name'] for idx in inspector.get_indexes('sleep')]
        if op.f('ix_sleep_id') in sleep_indexes:
            op.drop_index(op.f('ix_sleep_id'), table_name='sleep')

    if 'reflections' in tables:
        reflections_indexes = [idx['name'] for idx in inspector.get_indexes('reflections')]
        if op.f('ix_reflections_user_id') in reflections_indexes:
            op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
        if op.f('ix_reflections_id') in reflections_indexes:
            op.drop_index(op.f('ix_reflections_id'), table_name='reflections')
        if op.f('ix_reflections_date') in reflections_indexes:
            op.drop_index(op.f('ix_reflections_date'), table_name='reflections')

    if 'mood' in tables:
        mood_indexes = [idx['name'] for idx in inspector.get_indexes('mood')]
        if op.f('ix_mood_id') in mood_indexes:
            op.drop_index(op.f('ix_mood_id'), table_name='mood')

    if 'expenses' in tables:
        expenses_indexes = [idx['name'] for idx in inspector.get_indexes('expenses')]
        if op.f('ix_expenses_id') in expenses_indexes:
            op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
        
        expenses_columns = [col['name'] for col in inspector.get_columns('expenses')]
        if 'type' in expenses_columns:
            op.drop_column('expenses', 'type')

    if 'daily_journals' in tables:
        daily_journals_indexes = [idx['name'] for idx in inspector.get_indexes('daily_journals')]
        if op.f('ix_daily_journals_id') in daily_journals_indexes:
            op.drop_index(op.f('ix_daily_journals_id'), table_name='daily_journals')

    if 'system_configs' in tables:
        system_configs_indexes = [idx['name'] for idx in inspector.get_indexes('system_configs')]
        if op.f('ix_system_configs_key') in system_configs_indexes:
            op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
        op.drop_table('system_configs')
    # ### end Alembic commands ###